### ISSUE TITLE
Getting error: Include of non-modular header inside framework module

### ISSUE THREAD

**Issue by iiimartin** [apotocki/libssh2-iosx#1]
Hi!
I have installed the pods in some framework and when I try to import the header files into objective c classes I get following error:

Include of non-modular header inside framework module 'MyFramework.NMSSH': '.../iosApp/Pods/Headers/Public/libssh2-iosx/libssh2.h'

I am importing like:
#import "libssh2.h"
#import "libssh2_sftp.h"

**Comment by apotocki** [comment]
I can't repeat your problem. Can you create and share a minimal project that reproduces the error?

**Comment by iiimartin** [comment]
I have a framework in my project and I have added NMSSH classes from: https://github.com/NMSSH/NMSSH in that framework, also I have added pods for openssl and libssh in that framework.

I have added pods for openSSL, and libssh like:
`
target 'MyFramework' do
use_frameworks! 
  pod 'openssl-iosx', '~> 1.1.1o'
  pod 'libssh2-iosx', '~> 1.10.0'
end
`
I have imported libssh2.h and libssh_sftp.h files in NMSSH.h, like:
`
#import "libssh2.h"
#import "libssh2_sftp.h"
`
  
 I get the error in the import while building the framework.
 
 Hope this helps you!

**Comment by apotocki** [comment]
I've created an empty ios App project, added Podfile with openssl and libssh2 pods, run 'pod install', opened xcworkspace file obtained in the previous step, added an empty m file to the project, added lines with `#import "libssh2.h" #import "libssh2_sftp.h"`, added a simple function that calls some libssh2 function, gone to Project settings and add libz.tbd to "Link Binary With Library" section. And successfully built the project without any error. In addition, I checked that "Allow Non-modular Includes in Framework Modules" flag in the build setting has its default value - False. So I can't reproduce your problem, and have to repeat my previous question: Can you create and share a minimal project that reproduces the error?
